[context.production]
  publish = "public/"
  command = "yarn build"

[template.environment]
  GATSBY_MY_APP_NAME="Display name for your app"
  GATSBY_MY_APP_ID="Midtype Project ID"
  GATSBY_MY_APP_ENDPOINT="Midtype Project Endpoint"
  GATSBY_MY_APP_REDIRECT_URL="Where users should be redirected on login"
  GATSBY_MIDTYPE_API_KEY="An API key from your Midtype project"
